spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/osahaneat
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
