spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/osahaneat
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

Jwt:
  privateKey: ZOL0PReUD+U92owAeNRkFBs4PvmyYi3Jep3v8QuW5FI=

fileUpLoad:
  rootPath: /Users/khangnguyen/Desktop/uploads